2016-05-26 11:34:57,947 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 12:00:52,114 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 12:26:15,354 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 12:34:43,176 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 15:15:29,117 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 15:26:18,322 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 15:47:16,042 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 16:01:13,979 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 16:07:23,279 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 16:09:53,833 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 16:41:55,666 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 17:05:39,806 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 17:06:38,036 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 17:13:07,552 INFO  - MassTransit v2.9.2/v2.9.0.0, .NET Framework v4.0.30319.42000
2016-05-26 17:13:25,875 ERROR - Failed to retrieve Notifications for selected user.
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: Cannot open database "HrMaxx" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HrMaxx.Common.Repository.Notifications.NotificationRepository.GetNotifications(String LoginId) in c:\Dev\EDPI\Source\Zion\Zion.Common.Repository\Notifications\NotificationRepository.cs:line 24
   at HrMaxx.Common.Services.Notifications.NotificationService.GetNotifications(String LoginId) in c:\Dev\EDPI\Source\Zion\Zion.Common.Services\Notifications\NotificationService.cs:line 25
2016-05-26 17:13:25,899 ERROR - Get Notifications
HrMaxx.Infrastructure.Exceptions.HrMaxxApplicationException: Failed to retrieve Notifications for selected user. ---> System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.Data.SqlClient.SqlException: Cannot open database "HrMaxx" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HrMaxx.Common.Repository.Notifications.NotificationRepository.GetNotifications(String LoginId) in c:\Dev\EDPI\Source\Zion\Zion.Common.Repository\Notifications\NotificationRepository.cs:line 24
   at HrMaxx.Common.Services.Notifications.NotificationService.GetNotifications(String LoginId) in c:\Dev\EDPI\Source\Zion\Zion.Common.Services\Notifications\NotificationService.cs:line 25
   --- End of inner exception stack trace ---
   at HrMaxx.Common.Services.Notifications.NotificationService.GetNotifications(String LoginId) in c:\Dev\EDPI\Source\Zion\Zion.Common.Services\Notifications\NotificationService.cs:line 31
   at HrMaxxAPI.Controllers.NotificationsController.<GetNotifications>b__0() in c:\Dev\EDPI\Source\Zion\HrMaxxAPI\Controllers\NotificationsController.cs:line 24
   at HrMaxxAPI.Controllers.BaseApiController.<>c__DisplayClassc`1.<MakeServiceCall>b__8() in c:\Dev\EDPI\Source\Zion\HrMaxxAPI\Controllers\BaseApiController.cs:line 88
   at HrMaxx.Infrastructure.Tracing.HrMaxxTrace.PerfTrace(Action todo, PerfTraceType traceType, Type source, String format, Object[] message) in c:\Dev\EDPI\Source\Zion\Zion.Infrastructure\Tracing\ZionTrace.cs:line 20
   at HrMaxxAPI.Controllers.BaseApiController.MakeServiceCall[T](Func`1 callToMake, String traceMessage, Boolean handleNullAsNotFound) in c:\Dev\EDPI\Source\Zion\HrMaxxAPI\Controllers\BaseApiController.cs:line 88
